# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sch3lp's Blog
tagline:          'Yet another java developers blog.'
description:      'Blog of Tim Schraepen, java developer at Cegeka.'
url:              http://sch3lp.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Tim Schraepen'
  email:          sch3lp@gmail.com
  url:            http://twitter.com/timschraepen
  avatar:         http://www.gravatar.com/avatar/c9811dcdf2ab224aea0e1928e9422d07.png

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Sch3lp/sch3lp.github.io
