# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sch3lp's Blog
tagline:          'Yet another java developers blog.'
description:      'Blog of Tim Schraepen, java developer at Cegeka.'
url:              http://sch3lp.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Tim Schraepen'
  url:            http://twitter.com/timschraepen

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Sch3lp/sch3lp.github.io
